IF DB_ID(N'SocialMediaDb') IS NULL
BEGIN
	CREATE DATABASE [SocialMediaDb];
END;
GO

USE [SocialMediaDb];
GO

IF OBJECT_ID(N'dbo.Comments', N'U') IS NOT NULL
BEGIN
	DROP TABLE dbo.Comments;
END;
GO

IF OBJECT_ID(N'dbo.Posts', N'U') IS NOT NULL
BEGIN
	DROP TABLE dbo.Posts;
END;
GO

IF OBJECT_ID(N'dbo.Users', N'U') IS NOT NULL
BEGIN
	DROP TABLE dbo.Users;
END;
GO

CREATE TABLE dbo.Users
(
	UserId INT IDENTITY(1,1) NOT NULL,
	Phone VARCHAR(10) NOT NULL,
	UserName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(256) NOT NULL,
	PasswordHash NVARCHAR(MAX) NOT NULL,
	CoverImagePath NVARCHAR(500) NULL,
	Biography NVARCHAR(500) NULL,
	CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT SYSUTCDATETIME(),
	CONSTRAINT PK_Users PRIMARY KEY CLUSTERED (UserId),
	CONSTRAINT UQ_Users_Phone UNIQUE (Phone)
);
GO

CREATE TABLE dbo.Posts
(
	PostId INT IDENTITY(1,1) NOT NULL,
	UserId INT NOT NULL,
	Content NVARCHAR(2000) NOT NULL,
	ImagePath NVARCHAR(500) NULL,
	CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Posts_CreatedAt DEFAULT SYSUTCDATETIME(),
	CONSTRAINT PK_Posts PRIMARY KEY CLUSTERED (PostId),
	CONSTRAINT FK_Posts_Users_UserId FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId)
);
GO

CREATE TABLE dbo.Comments
(
	CommentId INT IDENTITY(1,1) NOT NULL,
	UserId INT NOT NULL,
	PostId INT NOT NULL,
	Content NVARCHAR(1000) NOT NULL,
	CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Comments_CreatedAt DEFAULT SYSUTCDATETIME(),
	CONSTRAINT PK_Comments PRIMARY KEY CLUSTERED (CommentId),
	CONSTRAINT FK_Comments_Users_UserId FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId),
	CONSTRAINT FK_Comments_Posts_PostId FOREIGN KEY (PostId) REFERENCES dbo.Posts(PostId)
);
GO

CREATE INDEX IX_Posts_CreatedAt_DESC ON dbo.Posts (CreatedAt DESC);
GO

CREATE INDEX IX_Comments_PostId ON dbo.Comments (PostId);
GO
